### ISSUE TITLE
replace tidyverse dependency by only required components

### ISSUE THREAD

**Issue by mabafaba** [unhcr/koboloadeR#31]
tidyverse is not recommended as a package dependency; better to load directly the few components we need like ggplot, dplyr. Should speed up installation by a lot. Also I think CRAN really doesn't like it

**Comment by Edouard-Legoupil** [comment]
I think it's fixed now

**Comment by mabafaba** [comment]
I think it still imports `tidyverse` (at least on the master & dev branches)?
https://github.com/unhcr/koboloadeR/blob/234fab7162adbe2c61d320c56cbe454a0af793d1/DESCRIPTION#L92
