### ISSUE TITLE
Maximum upload size exceeded "Select the File for the Data"

### ISSUE THREAD

**Issue by itsalllgood** [unhcr/koboloadeR#40]
Shiny App window disappear when you click "Build Data Dictionary"
![image](https://user-images.githubusercontent.com/6582588/57215878-86719100-6fee-11e9-998e-a73591944a46.png)

**Comment by maherdaoud** [comment]
To solve this issue you need to run this code before starting the app
`options(shiny.maxRequestSize=10000*1024^2)`

**Comment by Edouard-Legoupil** [comment]
Just updated the shiny app with the last version - please uninstall the package - then re-install and use the new shinyapp - 


```
kobo_shiny("app_main_koboloadeR.R")
```
