### ISSUE TITLE
Instance ID and Cluster ID unable to move to next screen

### ISSUE THREAD

**Issue by itsalllgood** [unhcr/koboloadeR#41]
Error "missing values are not allowed in subscripted assignments of data frames"
Instance ID and Cluster ID unable to move to next screen
![image](https://user-images.githubusercontent.com/6582588/57222975-d22f3500-7004-11e9-8341-d42711184602.png)

**Comment by Edouard-Legoupil** [comment]
This is not a bug - it's a project configuration issue - you need to select the correct unique ID to link the parent and child table.

Usually in kobo, you should look for something like instanceID - Having said that we can provide more details in the interface
