### ISSUE TITLE
Result of Multiple choice doesnt display for some questions.

### ISSUE THREAD

**Issue by JamesLeonDufour** [unhcr/koboloadeR#72]
For some Multiple choice questions the output doesnt show up, 

![image](https://user-images.githubusercontent.com/6214012/102932776-e8566700-446e-11eb-9786-18be4357845f.png)

Multiple choice question
No responses or the same answer was given (only one modality) recorded for this question.

## Context
Crunching data from Kobo, no specific error.

## Problem
Multiple choice question
No responses or the same answer was given (only one modality) recorded for this question.

## Expected result
Display of the multiple choice result

## Current result
For some Multiple choice questions the output doesnt show up, 

```r
# insert reprex here
```

## Possible Fix
__not obligatory, but suggest fixes or reasons for the bug__

## `name of issue` screenshot
__if relevant, include a screenshot__

**Comment by Edouard-Legoupil** [comment]
thanks! Fixed
